### ISSUE TITLE
Parsing Error (arpeggio.NoMatch) For a Clean PEG Grammar Using Backslashes

### ISSUE THREAD

**Issue by AurelienAtAvelia** [textX/Arpeggio#48]
A parsing error occurs (arpeggio.NoMatch) by using backslashes in the clean PEG grammar : 

```
from arpeggio.cleanpeg import ParserPEG
ParserPEG(
     """
         hash = "{" double_quote "=>" double_quote "}"
         double_quote = r'"(?:[^\\"]|\\")+"'
     """, "hash").parse('{ "hello" => "world" }')
```

**Comment by igordejanovic** [comment]
Hi @AurelienAtAvelia 
This works as expected. You have to account that backslashes are used as escape chars in Python string also. So either you have to use 4 backslashes in your regex or the grammar should be given as Python raw string (prepend `r` before grammar string starts).

**Comment by AurelienAtAvelia** [comment]
Hi Igor,

Thanks for replying, it works as expected by using 4 backslashes as you mentionned. Thanks!
Aurélien
