### ISSUE TITLE
ZeroOrMore gobbles syntax errors

### ISSUE THREAD

**Issue by soos-peter-levente** [textX/Arpeggio#53]
Hi!

First off, compliments on the wonderful tool. It makes life so much easier! 

But here's the but. Take this grammar...
```
def obj():         return "{", Optional(pair_list), "}"
def number():      return _("\d+")
def value():       return [ obj, number ]
def key():         return _("[a-zA-Z]+")
def pair():        return key, ":", value
def pair_list():   return pair, ZeroOrMore(",", pair)
def head():        return "[", key, "]"
def sect():        return head, ZeroOrMore(pair)
```
...and apply it to a string formatted in this way (note the comma syntax error after `d:1,`):
```
[SECTION]
a: 1
b: {c: 1,d:1,}
```
```
>>> ParserPython(sect).parse("[SECTION]\na:1\nb:{c:2,d:3,}")
[ [  '[' [0], key 'SECTION' [1],  ']' [2] ], [ key 'a' [4],  ':' [5], [ number '1' [6] ] ] ]
>>> _
```

In this parse tree, the entire contents of `b` got thrown out because of `ZeroOrMore`, sensibly I must add, since its docstring explicitly states that it will never fail. The problem is that whatever goes on in there is invisible and silent. 

_Verily_, the parent process (`visit_parse_tree` for one) ends up receiving a perfectly well-formed parse tree, and it has no way of knowing that there was some kind of mistake.  `pair` could resolve in an arbitrarily complex manner, and the input could be of arbitrary size (which is important because the developer has no hints about the precise point of failure).
 
So, would you consider an option to have `ZeroOrMore` print NoMatch exceptions and failure locations (if debugging mode is enabled, for example)? 

On the user level, it would be a great help to have a validating pass similar to `parseAll` in `pyparsing`. If set to `True`, the parser must match the entire string or fail (and print the deepest point from which  it could not proceed further). 

Maybe there is an analogous feature in Arpeggio already? If there isn't, I'd appreciate it if you considered adding one.

Thanks!

**Comment by igordejanovic** [comment]
Hi! Arpeggio is using a bit different approach to this. It might be better of worse YMMV. The idea is to specify whether you want the whole string to be matched or not by making that explicit in the grammar itself. If you end your root rule with `EOF` then you are effectively anchoring the end of the grammar to the end of the input and you'll receive the error at the begining of `b` stating that either `pair` or `EOF` is expected at that point. So, try changing your `sect` rule to be:

```
def sect():        return head, ZeroOrMore(pair), EOF
```

**Comment by soos-peter-levente** [comment]
It makes absolute sense once you point it out and it fixes the problem. I think it is a tad implicit, though, so it could be useful to document it as a feature so that other people can learn about the approach quickly.

Thank you for the help!

**Comment by igordejanovic** [comment]
Yes, absolutely. If should be documented. I'll leave this open until it is mentioned in the docs.
