### ISSUE TITLE
Replace use of imp library with importlib

### ISSUE THREAD

**Issue by mcepl** [textX/Arpeggio#54]
``imp`` has been deprecated a long time ago, and it is going to be removed soon.

[imp-to-importlib.patch](https://github.com/textX/Arpeggio/files/3278066/imp-to-importlib.patch.txt) replaces use of ``imp`` library with ``importlib`` for Python 3 (Python 2 support is still maintained via ``imp``).

I am sorry for not providing a proper pull request, but I am a Python maintainer in SUSE and this is just one of many packages I maintain.

**Comment by igordejanovic** [comment]
Applied. Thanks for the contribution!

**Comment by mcepl** [comment]
Actually, there is an updated version, which actually really passes the test suite.
