### ISSUE TITLE
Triple quoted strings in PEG

### ISSUE THREAD

**Issue by rysson** [textX/Arpeggio#60]
Hi,

It's possible to use triple quoted strings in PEG like in Python (https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str)?

It's useful in regex, example
```peg
quoted <- r'''(["'])(?P<value>\w*)\1''';
```

Now it looks like empty string (`''`) in PEG.

**Comment by igordejanovic** [comment]
If you want Python string syntax/semantics why don't you just use [Python to specify the grammar](http://textx.github.io/Arpeggio/stable/grammars/#grammars-written-in-python)?
What exactly would you need from triple quoted string?

BTW, two forms of PEG are implemented using canonical form based on Python language so it would be relatively straightforward to extend the implementation to suit your needs. See [here](https://github.com/textX/Arpeggio/blob/master/arpeggio/peg.py) and [here](https://github.com/textX/Arpeggio/blob/master/arpeggio/cleanpeg.py) for two flavors of PEG.

**Comment by rysson** [comment]
Thanks for quick answer. Example was in issue, using `'` and `"` together in regexp.

You point me an extension of PEG, thanks a lot.
It's enough for me. I'm closing the issue.
