### ISSUE TITLE
setup.py doesn't promise Python 3 compatibility

### ISSUE THREAD

**Issue by 1fish2** [textX/Arpeggio#65]
The `CHANGELOG.md` is clear that Arpeggio supports Python 3 but the [caniusepython3](https://github.com/brettcannon/caniusepython3) tool lists Arpeggio among projects that "need to transition to Python 3."

AIUI, to fix this, add these classifiers to `setup.py`:

    Programming Language :: Python :: 3.5
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7

**Comment by igordejanovic** [comment]
@1fish2 Fixed. Thanks for reporting. This will be a part of the next bugfix release which is about to happen.
