### ISSUE TITLE
Indentation based languages

### ISSUE THREAD

**Issue by mathrb** [textX/Arpeggio#74]
Hello

I know pure PEG cannot parse an indentation based language.
But like pegjs, Arpeggio might have a way to do it.

Do you thinks it's feasible? If yes, could you give me some hints?

Kind regards

**Comment by igordejanovic** [comment]
Hi
Yes, I think it is feasible but never got a change to put some time into it. There is some [discussion on the textX issue](https://github.com/textX/textX/issues/44).

There are two task/issues to be decided/solved:
1. How to track indentation level during recursive descend.
2. How to specify indentation language rules in the grammar.

For the second point what comes to mind is either to introduce a new `Match` subclasses `Indent` and `Dedent` and insert it at the place in the grammar where increasing/decreasing of indentation level is expected. Another way to deal with it is to introduce a parsing expression `Indented` which wraps other expression that are expected to be at the higher indentation level. Everything should be backward compatible regarding whitespace skipping. Also, what is considered an indentation increase (tabs/spaces, how many?) should be configurable.

**Comment by mathrb** [comment]
Thanks for your answer @igordejanovic 
The grammar I have highly depends on tracking indentation, so it might be complicated to implement.
Thanks

**Comment by charles-esterbrook** [comment]
FYI the PyParsing project recently introduced an IndentedBlock class to handle this (previously they used a helper method). Code and docs (same MIT license) at https://github.com/pyparsing/pyparsing/commit/2dd2e2bb70407eea91f18de2caea5ba4527eb7dc

**Comment by mnaderhirn** [comment]
Is there a plan to implement such a feature?

**Comment by igordejanovic** [comment]
I don't have resources to work on this but I would be glad to help out in discussing the design and reviewing the implementation if anyone has time and will to work on it.

**Comment by mnaderhirn** [comment]
I would be interested in doing it, but I would need guidance since I am not familiar with TextX itself, just its application
