### ISSUE TITLE
Match until end of line

### ISSUE THREAD

**Issue by cratuki** [textX/Arpeggio#84]
I am writing a grammar for a DSL where I want to use bash/python style comments. That is, a hash where the rest of the line is ignored. Apart from that, I do want newlines to behave as whitespace.

The arpeggio `__init__` offers a match token for EOF. Could one also be added for EOL?

There may be a way to do this already. If so, could we bring an example into examples/? I'm happy to work on an example if someone can show me the technique for getting past this.

For the moment, I am working around this problem by doing a line-by-line pre-transform of my document to replace hash lines with "comment { content }".

Here is an example of what I am seeking to do,
```
SAMPLE = '''
# This is a comment

class example;
'''

def _word():        return _(r'\w+')
def _class():       return 'class', _word, ';'
def _comment():     return '#', _(r'([^\n]*'), EOL
def _grammar():     return OneOrMore(_comment, _class), EOF
```

**Comment by igordejanovic** [comment]
You can start with the [simple language example](https://github.com/textX/Arpeggio/blob/master/examples/simple/simple.py). There you have a C like comments.

BTW, if you are building a DSL I highly suggest to take a look at [textX](http://textx.github.io/textX/stable/), which build on top of Arpeggio and is geared towards DSL development.

**Comment by cratuki** [comment]
I watched the textX video, that's powerful stuff. Thanks.
