### ISSUE TITLE
Can PEG syntax (cleanpeg) use reduce_tree and memoization?

### ISSUE THREAD

**Issue by Doomsk** [textX/Arpeggio#97]
I was trying to generate a reduced parse tree from `arpeggio.cleanpeg`'s `ParserPEG` with no success. I checked its implementation and it seems it use a method `_from_peg` to generate the parse tree, where it contains `ParserPython` with `reduced_tree=False`. I tried to write my own `ParserPEG`'s `_from_peg` using exactly the same code as placed on `cleanpeg.ParserPEG` now with both `reduce_tree` and `memoization` set as `True`, however it hasn't affected the .dot file result.

Any clues?

**Comment by igordejanovic** [comment]
Internal usage of `ParserPython` is for parsing the cleanpeg grammar. That shouldn't be reduced as visitor operates on a non-reduced tree. What you can use, since the `ParserPEG` of both `peg` and `cleanpeg` variants inherits `Parser`, is to pass `reduce_tree=True` directly to `ParserPEG` constructor. This should work (based on calc example):

```python
from arpeggio.cleanpeg import ParserPEG
calc_grammar = open(os.path.join(os.path.dirname(__file__),
                                     'calc_clean.peg'), 'r').read() 
parser = ParserPEG(calc_grammar, "calc", debug=True, reduce_tree=True)
parse_tree = parser.parse("-(4-1)*5+(2+4.67)+5.89/(.2+7)")
# parse_tree should be in a reduced form
```

**Comment by Doomsk** [comment]
for some reason doesn't seem to work on either `calc_clean.peg` example nor mine. Single non-terminal nodes are kept. Maybe something on the version 2.0.0 has changed something?

**Comment by igordejanovic** [comment]
That's strange. I don't recall any change that would influence that behavior. Release 2.0 was mainly dropping of Python 2 support (it might still work but there is no guarantee anymore). What version do you use? Can you check with current `master` version?

**Comment by Doomsk** [comment]
I'm using the pypi version (Arpeggio==2.0.0) on Linux.

**Comment by igordejanovic** [comment]
Here is a minimal test. Tested with 2.0.0 and the current master version.

```python
from arpeggio.cleanpeg import ParserPEG

grammar = r'''
S =  A / B
A = 'a'
B = 'b'
'''

parser = ParserPEG(grammar, 'S')
tree = parser.parse('b')

assert tree.__class__.__name__ == 'NonTerminal'
assert len(tree) == 1

parser = ParserPEG(grammar, 'S', reduce_tree=True)
tree = parser.parse('b')

assert tree.__class__.__name__ == 'Terminal'

```

**Comment by Doomsk** [comment]
After uninstalling and reinstalling the package from pip, it just... worked. I still cannot understand what happened, but I'm glad now things are as expected. Thank you for your time @igordejanovic !
